dist: xenial
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
matrix:
  include:
    - python: "3.7"
      env: TOXENV=lint
install: pip install tox tox-travis
script: tox
cache: pip
